#!/bin/bash

bat_perc="$(cat /sys/class/power_supply/BAT0/capacity)"

if [[ $(cat /sys/class/power_supply/BAT0/status ) == "Discharging" ]]; 
then
  charging=""
else
  charging="(󰚥) "
fi

echo -e "${bat_perc}% ${charging}"

